### ISSUE TITLE
Add potential roadblock items to the marker sprite set

### ISSUE THREAD

**Issue by LeonPow** [ericlakatos/windfish-issues#12]
Requesting that we be able to mark up tiles with the sprites for the Sword, Feather, Bracelet, Pegasus Boots, Flippers, Hookshot, and Bombs. 

Frequently progression in discovered caves is walled behind needing these items and this would be very useful in being able to note which items are needed to progress in which caves where the current notation for that is vague. This one is open for discussion because I feel that's partially by design and I'm not sure if this change would make progression tracking a bit too easy on the player. Discuss it in discord, perhaps?

**Comment by ericlakatos** [comment]
Completed
